### ISSUE TITLE
请教您之前的一篇的文章的配图是用如何制作的

### ISSUE THREAD

**Issue by dalei2019** [panjf2000/panjf2000#2]
首先，不确定在这里提问是否合适，如果不合适我可以在之后删除。
文章是在知乎上看到的[Linux I/O 原理和 Zero-copy 技术全面揭秘
](https://zhuanlan.zhihu.com/p/308054212)。
其中对零拷贝的解释真的是鞭辟入里，个人非常喜欢这个风格。
文章中您的配图清晰规整、配色舒适，所以非常想了解文中的配图是如何制作的。

**Comment by panjf2000** [comment]
用 sketch 画的，看到后麻烦删掉这个 issue，有事的话请给我发邮件。

**Comment by dalei2019** [comment]
已收到回复，谢谢您。
可以删除了，应该需要您操作下。
